# Generated by Django 4.2.3 on 2023-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_section_bold_alter_question_align_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('flex', 'Flex'), ('table', 'Table')], max_length=50),
        ),
    ]
