# Generated by Django 4.2.3 on 2023-10-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_section_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
