# Generated by Django 4.2.3 on 2023-10-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_response_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='line_below',
            field=models.BooleanField(default=False),
        ),
    ]
