# Generated by Django 4.2.3 on 2023-10-31 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0007_form_line_below'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
