# Generated by Django 4.2.3 on 2023-11-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_form_form_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='line_below',
        ),
    ]
