# Generated by Django 4.2.3 on 2023-11-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_remove_form_line_below'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img_input',
            field=models.BooleanField(default=False),
        ),
    ]
