# Generated by Django 4.2.3 on 2023-12-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_question_img_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='line_below',
            field=models.BooleanField(default=False),
        ),
    ]
